name: Continuous Integration Workflow
on: push

jobs:
  build:
    name: Test and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List the repository
        run: ls -A
