name: Continuous Integration Workflow
on: push

jobs:
  build:
    name: Test and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Gems
        run: bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Run Tests
        run: bundle exec ruby -I lib test/runAllTests.rb
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "fierce-hamlet-5053"
        if: github.ref == 'refs/heads/withLimitedData' && job.status == 'success'
        run: |
          git push \
            https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git \
            origin/withLimitedData:master
