name: Continuous Integration Workflow
on: push

jobs:
  build:
    name: Test and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Install RVM
        run: curl -sSL https://get.rvm.io | bash -s stable
      - name: Install Ruby
        run: rvm install 2.3.1
      - uses: actions/checkout@v2
      - run: bundle --version
      - run: ls -A
