name: Continuous Integration Workflow
on: push

jobs:
  build:
    name: Test and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: what is the directory
        run: pwd
      - name: List the repository
        run: ls
