name: Continuous Integration Workflow
on: push

jobs:
  build:
    name: Test and Publish
    runs-on: ubuntu-latest
    steps:
      - name: List the repository
        run: ls
      - name: Check Ruby's version
        run: ruby --version
      - name: Create an error
        run: ls something_that_doesnt_exist
      - name: Will this action run?
        run: echo It ran
