name: Continuous Integration Workflow
on: push

jobs:
  build:
    name: Test and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - uses: actions/checkout@v2
      - run: bundle --version
      - run: ls -A
