on:
  push:
    branches:
      - main

jobs:
  fly:
      name: Fly
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Use repository's data
          run: sed -i "s/data\/sample/${{vars.KLALUMIERE_CVCREATOR_DATA_PATH}}/" fly.toml
        - name: Deployment
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          run: flyctl deploy --detach --ha=false --remote-only
