on:
  push:
    branches:
      - main

jobs:
  fly:
      name: Fly
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Deployment
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          run: |
            flyctl deploy \
              --detach \
              --max-concurrent 1 \
              --max-unavailable 1 \
              --remote-only
