name: Test

on:
  push:
    branches:
      - '!master'

jobs:
  deploy:
      name: Test app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: |
            sudo apt install --assume-yes --no-install-recommend leiningen
        - name: Unit tests
          run: lein test
