on:
  push: {}

jobs:
  ci-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            --assume-yes \
            --no-install-recommends \
              leiningen
      - name: Unit Tests
        run: lein test
      - name: Integration Tests
        run: lein test :integration
      - name: Packaging Test
        run: lein ring uberjar
      - name: End to End Tests
        env:
          CV_CREATOR_SPECS_INSTRUMENTED: "true"
        run: |
          lein run -m cv-creator.core/-main data/sample english | grep "Alain Térieur"
          lein run -m cv-creator.core/-main data/sample french | grep "Alex Térieur"
          lein run -m cv-creator.core/-main data/sample english computerScience | grep "Titus"
          ! lein run -m cv-creator.core/-main data/sample english | grep "Titus"
  
  ci-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm test
