on:
  push: {}

jobs:
  ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install \
              --assume-yes \
              --no-install-recommends \
                leiningen
        - name: Unit Tests
          run: lein test
        - name: Packaging Test
          run: lein ring uberjar
        - name: End to End Tests
          run: lein run -m cv-creator.core/-main | grep "Alain Térieur"
